# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administor/Desktop/Logical/Logical1/Logical1.cache/wt [current_project]
set_property parent.project_path C:/Users/Administor/Desktop/Logical/Logical1/Logical1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administor/Desktop/Logical/Logical1/Logical1.srcs/sources_1/new/T1_B.v
  C:/Users/Administor/Desktop/Logical/Logical1/Logical1.srcs/sources_1/new/T1_B_All.v
}
read_xdc C:/Users/Administor/Desktop/Logical/Logical1/Logical1.srcs/constrs_1/new/T1.xdc
set_property used_in_implementation false [get_files C:/Users/Administor/Desktop/Logical/Logical1/Logical1.srcs/constrs_1/new/T1.xdc]

synth_design -top T1_B_All -part xc7a100tcsg324-1
write_checkpoint -noxdef T1_B_All.dcp
catch { report_utilization -file T1_B_All_utilization_synth.rpt -pb T1_B_All_utilization_synth.pb }
